name: QSAR_environment_gpu
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10.18
  - pip
  - numpy=1.26.4
  - pandas=2.3.2
  - scipy=1.13.1
  - rdkit=2025.03.6
  - scikit-learn=1.7.1
  - imbalanced-learn=0.14.0
  - lightgbm=4.5.0
  - numba=0.61.2
  - joblib=1.5.2
  - threadpoolctl=3.6.0
  - cuda-version=12.0
  - cuda-nvrtc=12.0.76
  - libxgboost=3.0.4
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - openpyxl=3.1.5
  - et_xmlfile=2.0.0
  - tqdm=4.67.1
  - psutil=7.0.0
  - pyyaml=6.0.2
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - tzdata=2025b

  - pip:
      # QSAR core
      - pyarrow==21.0.0
      - shap==0.45.1
      - xgboost==2.0.3
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio==2.8.0
      - triton==3.4.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - pytorch-tabnet==4.1.0
      - scikeras==0.13.0
      - skorch==1.2.0
