name: QSAR_environment_cpu
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10.18
  - pip
  - numpy=1.26.4
  - pandas=2.3.2
  - scipy=1.13.1
  - rdkit=2025.03.6
  - scikit-learn=1.7.1
  - imbalanced-learn=0.14.0
  - lightgbm=4.5.0
  - numba=0.61.2
  - joblib=1.5.2
  - threadpoolctl=3.6.0
  - matplotlib=3.10.6
  - seaborn=0.13.2
  - openpyxl=3.1.5
  - et_xmlfile=2.0.0
  - tqdm=4.67.1
  - psutil=7.0.0
  - pyyaml=6.0.2
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - tzdata=2025b

  - pip:
      - pyarrow==21.0.0
      - shap==0.45.1
      - xgboost==2.0.3
